CAPNP_SCHEMA=request.capnp
BACKEND_DIR=backend

CAPNP_GO_SUBMODULE=$(BACKEND_DIR)/go-capnp
CAPNP_GO_BINDINGS=$(BACKEND_DIR)/$(CAPNP_SCHEMA).go
CAPNP_GO_STDLIB=$(CAPNP_GO_SUBMODULE)/std

.PHONY: all
all: help

.PHONY: lint
lint: ## Run the golangci linter
	golangci-lint run

.PHONY: test
test: ## Run the application unit tests
	go test -v ./backend/...

.PHONY: dev
dev: $(CAPNP_GO_BINDINGS) ## Run the application back-end inside nonodo
	nonodo -- go run ./backend

.PHONY: build
build: $(CAPNP_GO_BINDINGS) ## Build the application RISC-V image with sunodo
	sunodo build

.PHONY: run
run: ## Run the application back-end in the Cartesi Machine with sunodo
	sunodo run

.PHONY: clean
clean: ## Delete the application RISC-V image generated by sunodo
	rm -rf .sunodo

.PHONY: help
help: ## Show help for each of the Makefile recipes
	@grep "##" $(MAKEFILE_LIST) | grep -v grep | sed -e 's/:.*##/:\t/'

$(CAPNP_GO_BINDINGS): $(CAPNP_GO_STDLIB) $(CAPNP_SCHEMA)
	capnp compile -I $(CAPNP_GO_STDLIB) -ogo:$(BACKEND_DIR) $(CAPNP_SCHEMA)

$(CAPNP_GO_STDLIB): $(CAPNP_GO_SUBMODULE)
	git submodule update --init --recursive
