CAPNP_SCHEMA=calculator.capnp

CAPNP_GO_SUBMODULE=go-capnp
CAPNP_GO_BINDINGS=${CAPNP_SCHEMA}.go
CAPNP_GO_STDLIB=${CAPNP_GO_SUBMODULE}/std

.PHONY: all
all: help

.PHONY: lint
lint: ## Run the golangci linter
	golangci-lint run

.PHONY: test
test: ## Run the application unit tests
	go test -v ./...

.PHONY: dev
dev: capnp ## Run the application inside nonodo
	nonodo -- go run .

.PHONY: build
build: capnp ## Build the application RISC-V image with sunodo
	sunodo build

.PHONY: capnp
capnp: ${CAPNP_GO_BINDINGS} ## Generate the Cap'n Proto bindings

.PHONY: run
run: ## Run the application in the Cartesi Machine with sunodo
	sunodo run

.PHONY: clean
clean: ## Delete the application RISC-V image generated by sunodo
	rm -rf .sunodo

${CAPNP_GO_BINDINGS}: ${CAPNP_GO_STDLIB} ${CAPNP_SCHEMA}
	capnp compile -I ${CAPNP_GO_STDLIB} -ogo ${CAPNP_SCHEMA}

${CAPNP_GO_STDLIB}: ${CAPNP_GO_SUBMODULE}
	git submodule update --init --recursive

.PHONY: help
help: ## Show help for each of the Makefile recipes
	@grep "##" $(MAKEFILE_LIST) | grep -v grep | sed -e 's/:.*##/:\t/'
